/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseButtons: typeof import('./components/ui-components/button/BaseButtons.vue')['default']
    Basic: typeof import('./components/ui-components/alert/Basic.vue')['default']
    CardHeaderFooter: typeof import('./components/shared/CardHeaderFooter.vue')['default']
    CardsContentWrap: typeof import('./components/ui-components/cards/CardsContentWrap.vue')['default']
    CardsMedia: typeof import('./components/ui-components/cards/CardsMedia.vue')['default']
    CardsProps: typeof import('./components/ui-components/cards/CardsProps.vue')['default']
    CardsSlots: typeof import('./components/ui-components/cards/CardsSlots.vue')['default']
    CardsTwitter: typeof import('./components/ui-components/cards/CardsTwitter.vue')['default']
    CardsWeather: typeof import('./components/ui-components/cards/CardsWeather.vue')['default']
    Closable: typeof import('./components/ui-components/alert/Closable.vue')['default']
    ColorsButtons: typeof import('./components/ui-components/button/ColorsButtons.vue')['default']
    DailyChart: typeof import('./components/dashboard/DailyChart.vue')['default']
    DefaultText: typeof import('./components/style-components/typography/DefaultText.vue')['default']
    FavoriteItems: typeof import('./components/dashboard/FavoriteItems.vue')['default']
    FeedbackCard: typeof import('./components/dashboard/FeedbackCard.vue')['default']
    Filled: typeof import('./components/ui-components/alert/Filled.vue')['default']
    Heading: typeof import('./components/style-components/typography/Heading.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconColorSizes: typeof import('./components/ui-components/button/IconColorSizes.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    OrderForm: typeof import('./components/OrderForm.vue')['default']
    OutlinedButtons: typeof import('./components/ui-components/button/OutlinedButtons.vue')['default']
    Page: typeof import('./components/category/page.vue')['default']
    ProductCard: typeof import('./components/dashboard/ProductCard.vue')['default']
    RecentOrders: typeof import('./components/dashboard/RecentOrders.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shadow: typeof import('./components/style-components/shadow/Shadow.vue')['default']
    SizeButtons: typeof import('./components/ui-components/button/SizeButtons.vue')['default']
    SumSection: typeof import('./components/dashboard/SumSection.vue')['default']
    TextButtons: typeof import('./components/ui-components/button/TextButtons.vue')['default']
    UiChildCard: typeof import('./components/shared/UiChildCard.vue')['default']
    UiParentCard: typeof import('./components/shared/UiParentCard.vue')['default']
    UiParentCardLogo: typeof import('./components/shared/UiParentCardLogo.vue')['default']
    UiTableCard: typeof import('./components/shared/UiTableCard.vue')['default']
    UiTextfieldPrimary: typeof import('./components/shared/UiTextfieldPrimary.vue')['default']
    Warning: typeof import('./components/dashboard/Warning.vue')['default']
    WidgetCard: typeof import('./components/shared/WidgetCard.vue')['default']
    WidgetCardv2: typeof import('./components/shared/WidgetCardv2.vue')['default']
  }
}
