/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Banners/': RouteRecordInfo<'/Banners/', '/Banners', Record<never, never>, Record<never, never>>,
    '/Banners/[id]/edit': RouteRecordInfo<'/Banners/[id]/edit', '/Banners/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Banners/create': RouteRecordInfo<'/Banners/create', '/Banners/create', Record<never, never>, Record<never, never>>,
    '/Category': RouteRecordInfo<'/Category', '/Category', Record<never, never>, Record<never, never>>,
    '/Coupons/': RouteRecordInfo<'/Coupons/', '/Coupons', Record<never, never>, Record<never, never>>,
    '/Customer/': RouteRecordInfo<'/Customer/', '/Customer', Record<never, never>, Record<never, never>>,
    '/Customization/': RouteRecordInfo<'/Customization/', '/Customization', Record<never, never>, Record<never, never>>,
    '/Customization/create': RouteRecordInfo<'/Customization/create', '/Customization/create', Record<never, never>, Record<never, never>>,
    '/Feedbacks/': RouteRecordInfo<'/Feedbacks/', '/Feedbacks', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/OrderManagement/': RouteRecordInfo<'/OrderManagement/', '/OrderManagement', Record<never, never>, Record<never, never>>,
    '/Products/': RouteRecordInfo<'/Products/', '/Products', Record<never, never>, Record<never, never>>,
    '/Products/[id]/edit': RouteRecordInfo<'/Products/[id]/edit', '/Products/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Products/create': RouteRecordInfo<'/Products/create', '/Products/create', Record<never, never>, Record<never, never>>,
    '/Promotions/': RouteRecordInfo<'/Promotions/', '/Promotions', Record<never, never>, Record<never, never>>,
    '/Promotions/[id]/edit': RouteRecordInfo<'/Promotions/[id]/edit', '/Promotions/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Promotions/create': RouteRecordInfo<'/Promotions/create', '/Promotions/create', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/Report': RouteRecordInfo<'/Report', '/Report', Record<never, never>, Record<never, never>>,
    '/Tables/': RouteRecordInfo<'/Tables/', '/Tables', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
